# Generated by Django 4.0.8 on 2024-10-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='content_creator',
        ),
    ]
