# Generated by Django 4.0.8 on 2024-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_bid_content_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='likes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='views',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
